name: Schema Validation

on:
  pull_request:
    branches:
      - Pending-AIPs

jobs:
  validate-shcema:
    name: schema-validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Parse Markdown
        run: npm run parse-markdown

      - name: Verify Schema
        run: npm run validation:aip-schema
